package lpg.grammars.swift_fin;

public interface SwiftFinLexersym {
    public final static int
      Char_LF = 5,
      Char_CR = 94,
      Char_HT = 3,
      Char_FF = 6,
      Char_a = 12,
      Char_b = 13,
      Char_c = 14,
      Char_d = 15,
      Char_e = 16,
      Char_f = 17,
      Char_g = 18,
      Char_h = 19,
      Char_i = 20,
      Char_j = 21,
      Char_k = 22,
      Char_l = 23,
      Char_m = 24,
      Char_n = 25,
      Char_o = 26,
      Char_p = 27,
      Char_q = 28,
      Char_r = 29,
      Char_s = 30,
      Char_t = 31,
      Char_u = 32,
      Char_v = 33,
      Char_w = 34,
      Char_x = 35,
      Char_y = 36,
      Char_z = 37,
      Char_A = 38,
      Char_B = 39,
      Char_C = 40,
      Char_D = 41,
      Char_E = 42,
      Char_F = 43,
      Char_G = 44,
      Char_H = 45,
      Char_I = 46,
      Char_J = 47,
      Char_K = 48,
      Char_L = 49,
      Char_M = 50,
      Char_N = 51,
      Char_O = 52,
      Char_P = 53,
      Char_Q = 54,
      Char_R = 55,
      Char_S = 56,
      Char_T = 57,
      Char_U = 58,
      Char_V = 59,
      Char_W = 60,
      Char_X = 61,
      Char_Y = 62,
      Char_Z = 63,
      Char_0 = 64,
      Char_1 = 7,
      Char_2 = 8,
      Char_3 = 9,
      Char_4 = 10,
      Char_5 = 11,
      Char_6 = 65,
      Char_7 = 66,
      Char_8 = 67,
      Char_9 = 68,
      Char_Space = 4,
      Char_LeftBrace = 69,
      Char_RightBrace = 70,
      Char_Colon = 2,
      Char_Minus = 71,
      Char__ = 72,
      Char_! = 73,
      Char_@ = 74,
      Char_# = 75,
      Char_$ = 76,
      Char_% = 77,
      Char_& = 78,
      Char_| = 79,
      Char_( = 80,
      Char_) = 81,
      Char_[ = 82,
      Char_] = 83,
      Char_. = 84,
      Char_, = 85,
      Char_= = 86,
      Char_+ = 87,
      Char_* = 88,
      Char_/ = 89,
      Char_< = 90,
      Char_> = 91,
      Char_' = 92,
      Char_" = 93,
      Char_EOF = 1;

    public static String[] orderedTerminalSymbols = {
                 "",
                 "EOF",
                 "Colon",
                 "HT",
                 "Space",
                 "LF",
                 "FF",
                 "1",
                 "2",
                 "3",
                 "4",
                 "5",
                 "a",
                 "b",
                 "c",
                 "d",
                 "e",
                 "f",
                 "g",
                 "h",
                 "i",
                 "j",
                 "k",
                 "l",
                 "m",
                 "n",
                 "o",
                 "p",
                 "q",
                 "r",
                 "s",
                 "t",
                 "u",
                 "v",
                 "w",
                 "x",
                 "y",
                 "z",
                 "A",
                 "B",
                 "C",
                 "D",
                 "E",
                 "F",
                 "G",
                 "H",
                 "I",
                 "J",
                 "K",
                 "L",
                 "M",
                 "N",
                 "O",
                 "P",
                 "Q",
                 "R",
                 "S",
                 "T",
                 "U",
                 "V",
                 "W",
                 "X",
                 "Y",
                 "Z",
                 "0",
                 "6",
                 "7",
                 "8",
                 "9",
                 "LeftBrace",
                 "RightBrace",
                 "Minus",
                 "_",
                 "!",
                 "@",
                 "#",
                 "$",
                 "%",
                 "&",
                 "|",
                 "(",
                 ")",
                 "[",
                 "]",
                 ".",
                 ",",
                 "=",
                 "+",
                 "*",
                 "/",
                 "<",
                 ">",
                 "'",
                 """,
                 "CR"
             };

    public final static int numTokenKinds = 94;


    public final static boolean isValidForParser = true;
}
