package lpg.grammars.swift_fin;

public interface SwiftFinKWLexersym {
    public final static int
      Char_DollarSign = 3,
      Char_Percent = 4,
      Char__ = 5,
      Char_0 = 6,
      Char_1 = 7,
      Char_2 = 8,
      Char_3 = 9,
      Char_4 = 10,
      Char_5 = 11,
      Char_6 = 12,
      Char_7 = 13,
      Char_8 = 14,
      Char_9 = 15,
      Char_a = 16,
      Char_b = 17,
      Char_c = 18,
      Char_d = 19,
      Char_e = 20,
      Char_f = 21,
      Char_g = 22,
      Char_h = 23,
      Char_i = 24,
      Char_j = 25,
      Char_k = 26,
      Char_l = 27,
      Char_m = 28,
      Char_n = 29,
      Char_o = 30,
      Char_p = 31,
      Char_q = 32,
      Char_r = 33,
      Char_s = 34,
      Char_t = 35,
      Char_u = 36,
      Char_v = 37,
      Char_w = 38,
      Char_x = 39,
      Char_y = 40,
      Char_z = 1,
      Char_Minus = 41,
      Char_EOF = 2;

    public static String[] orderedTerminalSymbols = {
                 "",
                 "z",
                 "EOF",
                 "DollarSign",
                 "Percent",
                 "_",
                 "0",
                 "1",
                 "2",
                 "3",
                 "4",
                 "5",
                 "6",
                 "7",
                 "8",
                 "9",
                 "a",
                 "b",
                 "c",
                 "d",
                 "e",
                 "f",
                 "g",
                 "h",
                 "i",
                 "j",
                 "k",
                 "l",
                 "m",
                 "n",
                 "o",
                 "p",
                 "q",
                 "r",
                 "s",
                 "t",
                 "u",
                 "v",
                 "w",
                 "x",
                 "y",
                 "Minus"
             };

    public final static int numTokenKinds = 41;


    public final static boolean isValidForParser = true;
}
