package lpg.grammars.json;

public interface JsonKWLexersym {
    public final static int
      Char_DollarSign = 11,
      Char_Percent = 12,
      Char__ = 13,
      Char_0 = 14,
      Char_1 = 15,
      Char_2 = 16,
      Char_3 = 17,
      Char_4 = 18,
      Char_5 = 19,
      Char_6 = 20,
      Char_7 = 21,
      Char_8 = 22,
      Char_9 = 23,
      Char_a = 4,
      Char_b = 24,
      Char_c = 25,
      Char_d = 26,
      Char_e = 2,
      Char_f = 5,
      Char_g = 27,
      Char_h = 28,
      Char_i = 29,
      Char_j = 30,
      Char_k = 31,
      Char_l = 1,
      Char_m = 32,
      Char_n = 6,
      Char_o = 33,
      Char_p = 34,
      Char_q = 35,
      Char_r = 7,
      Char_s = 8,
      Char_t = 9,
      Char_u = 3,
      Char_v = 36,
      Char_w = 37,
      Char_x = 38,
      Char_y = 39,
      Char_z = 40,
      Char_EOF = 10;

    public static String[] orderedTerminalSymbols = {
                 "",
                 "l",
                 "e",
                 "u",
                 "a",
                 "f",
                 "n",
                 "r",
                 "s",
                 "t",
                 "EOF",
                 "DollarSign",
                 "Percent",
                 "_",
                 "0",
                 "1",
                 "2",
                 "3",
                 "4",
                 "5",
                 "6",
                 "7",
                 "8",
                 "9",
                 "b",
                 "c",
                 "d",
                 "g",
                 "h",
                 "i",
                 "j",
                 "k",
                 "m",
                 "o",
                 "p",
                 "q",
                 "v",
                 "w",
                 "x",
                 "y",
                 "z"
             };

    public final static int numTokenKinds = 40;


    public final static boolean isValidForParser = true;
}
