package lpg.grammars.cobol85;

public interface Cobol85KWLexersym {
    public final static int
      Char_DollarSign = 29,
      Char_Percent = 30,
      Char__ = 31,
      Char_0 = 32,
      Char_1 = 33,
      Char_2 = 34,
      Char_3 = 35,
      Char_4 = 36,
      Char_5 = 37,
      Char_6 = 38,
      Char_7 = 39,
      Char_8 = 40,
      Char_9 = 41,
      Char_a = 6,
      Char_b = 16,
      Char_c = 11,
      Char_d = 9,
      Char_e = 1,
      Char_f = 17,
      Char_g = 12,
      Char_h = 19,
      Char_i = 2,
      Char_j = 26,
      Char_k = 21,
      Char_l = 8,
      Char_m = 15,
      Char_n = 4,
      Char_o = 10,
      Char_p = 13,
      Char_q = 23,
      Char_r = 5,
      Char_s = 7,
      Char_t = 3,
      Char_u = 14,
      Char_v = 20,
      Char_w = 22,
      Char_x = 24,
      Char_y = 18,
      Char_z = 25,
      Char_Minus = 27,
      Char_EOF = 28;

    public static String[] orderedTerminalSymbols = {
                 "",
                 "e",
                 "i",
                 "t",
                 "n",
                 "r",
                 "a",
                 "s",
                 "l",
                 "d",
                 "o",
                 "c",
                 "g",
                 "p",
                 "u",
                 "m",
                 "b",
                 "f",
                 "y",
                 "h",
                 "v",
                 "k",
                 "w",
                 "q",
                 "x",
                 "z",
                 "j",
                 "Minus",
                 "EOF",
                 "DollarSign",
                 "Percent",
                 "_",
                 "0",
                 "1",
                 "2",
                 "3",
                 "4",
                 "5",
                 "6",
                 "7",
                 "8",
                 "9"
             };

    public final static int numTokenKinds = 41;


    public final static boolean isValidForParser = true;
}
