package lpg.grammars.cobol85;

public interface Cobol85KWLexerexp {
    public final static int
      ABORT = 1,
      ACCEPT = 2,
      ACCESS = 3,
      ADATA = 4,
      ADD = 5,
      ADDRESS = 6,
      ADV = 7,
      ADVANCING = 8,
      AFTER = 9,
      ALIAS = 10,
      ALIGNED = 11,
      ALL = 12,
      ALPHABET = 13,
      ALPHABETIC = 14,
      ALPHANUMERIC = 15,
      ALSO = 16,
      ALTER = 17,
      ALTERNATE = 18,
      AND = 19,
      ANSI = 20,
      ANY = 21,
      APOST = 22,
      AR = 23,
      ARE = 24,
      AREA = 25,
      AREAS = 26,
      ARITH = 27,
      AS = 28,
      ASCENDING = 29,
      ASCII = 30,
      ASSIGN = 31,
      AT = 32,
      ATTRIBUTE = 33,
      AUTHOR = 34,
      AUTO = 35,
      AWO = 36,
      BASIS = 37,
      BEEP = 38,
      BEFORE = 39,
      BEGINNING = 40,
      BELL = 41,
      BIN = 42,
      BINARY = 43,
      BIT = 44,
      BLANK = 45,
      BLINK = 46,
      BLOCK = 47,
      BOTTOM = 48,
      BOUNDS = 49,
      BUF = 50,
      BUFSIZE = 51,
      BY = 52,
      BYFUNCTION = 53,
      BYTITLE = 54,
      CALL = 55,
      CANCEL = 56,
      CAPABLE = 57,
      CBL = 58,
      CBLCARD = 59,
      CCSVERSION = 60,
      CD = 61,
      CF = 62,
      CH = 63,
      CHAINING = 64,
      CHANGED = 65,
      CHANNEL = 66,
      CHARACTER = 67,
      CHARACTERS = 68,
      CICS = 69,
      CLASS = 70,
      CLOSE = 71,
      CO = 72,
      COBOL = 73,
      CODE = 74,
      CODEPAGE = 75,
      COL = 76,
      COLLATING = 77,
      COLUMN = 78,
      COMMA = 79,
      COMMITMENT = 80,
      COMMON = 81,
      COMMUNICATION = 82,
      COMP = 83,
      COMPAT = 84,
      COMPILE = 85,
      COMPUTATIONAL = 86,
      COMPUTE = 87,
      CONFIGURATION = 88,
      CONTAINS = 89,
      CONTENT = 90,
      CONTINUE = 91,
      CONTROL = 92,
      CONTROLS = 93,
      CONVENTION = 94,
      CONVERTING = 95,
      COPY = 96,
      CORR = 97,
      CORRESPONDING = 98,
      COUNT = 99,
      CP = 100,
      CPP = 101,
      CPSM = 102,
      CRUNCH = 103,
      CS = 104,
      CURR = 105,
      CURRENCY = 106,
      CURSOR = 107,
      DATA = 108,
      DATE = 109,
      DATEPROC = 110,
      DAY = 111,
      DBCS = 112,
      DD = 113,
      DE = 114,
      DEBUG = 115,
      DEBUGGING = 116,
      DECK = 117,
      DECLARATIVES = 118,
      DEFAULT = 119,
      DEFINITION = 120,
      DELETE = 121,
      DELIMITED = 122,
      DELIMITER = 123,
      DEPENDING = 124,
      DESCENDING = 125,
      DESTINATION = 126,
      DETAIL = 127,
      DFHRESP = 128,
      DFHVALUE = 129,
      DIAGTRUNC = 130,
      DISABLE = 131,
      DISK = 132,
      DISPLAY = 133,
      DIVIDE = 134,
      DIVISION = 135,
      DLI = 136,
      DLL = 137,
      DONTCARE = 138,
      DOUBLE = 139,
      DOWN = 140,
      DP = 141,
      DTR = 142,
      DU = 143,
      DUMP = 144,
      DUPLICATES = 145,
      DYN = 146,
      DYNAM = 147,
      DYNAMIC = 148,
      EBCDIC = 149,
      EDF = 150,
      EGCS = 151,
      EGI = 152,
      EJECT = 153,
      EJPD = 154,
      ELSE = 155,
      EMI = 156,
      EN = 157,
      ENABLE = 158,
      END = 159,
      ENDING = 160,
      ENGLISH = 161,
      ENTER = 162,
      ENTRY = 163,
      ENVIRONMENT = 164,
      EOL = 165,
      EOP = 166,
      EOS = 167,
      EPILOG = 168,
      EQUAL = 169,
      ERASE = 170,
      ERROR = 171,
      ESCAPE = 172,
      ESI = 173,
      EVALUATE = 174,
      EVENT = 175,
      EVERY = 176,
      EXCEPTION = 177,
      EXCI = 178,
      EXCLUSIVE = 179,
      EXEC = 180,
      EXHIBIT = 181,
      EXIT = 182,
      EXP = 183,
      EXPORT = 184,
      EXPORTALL = 185,
      EXTEND = 186,
      EXTENDED = 187,
      EXTERNAL = 188,
      FALSE = 189,
      FASTSRT = 190,
      FD = 191,
      FEPI = 192,
      FILE = 193,
      FILLER = 194,
      FINAL = 195,
      FIRST = 196,
      FLAG = 197,
      FLAGSTD = 198,
      FOOTING = 199,
      FOR = 200,
      FROM = 201,
      FSRT = 202,
      FULL = 203,
      FUNCTION = 204,
      FUNCTIONNAME = 205,
      GDS = 206,
      GENERATE = 207,
      GIVING = 208,
      GLOBAL = 209,
      GO = 210,
      GOBACK = 211,
      GRAPHIC = 212,
      GREATER = 213,
      GRID = 214,
      GROUP = 215,
      HEADING = 216,
      HIGHLIGHT = 217,
      HOOK = 218,
      ID = 219,
      IDENTIFICATION = 220,
      IF = 221,
      IMPLICIT = 222,
      IMPORT = 223,
      IN = 224,
      INDEX = 225,
      INDEXED = 226,
      INDICATE = 227,
      INITIAL = 228,
      INITIALIZE = 229,
      INITIATE = 230,
      INPUT = 231,
      INSPECT = 232,
      INSTALLATION = 233,
      INTDATE = 234,
      INTEGER = 235,
      INTO = 236,
      INVALID = 237,
      INVOKE = 238,
      IS = 239,
      JA = 240,
      JP = 241,
      JUST = 242,
      JUSTIFIED = 243,
      KA = 244,
      KANJI = 245,
      KEPT = 246,
      KEY = 247,
      KEYBOARD = 248,
      LABEL = 249,
      LANG = 250,
      LANGUAGE = 251,
      LAST = 252,
      LB = 253,
      LC = 254,
      LD = 255,
      LEADING = 256,
      LEASM = 257,
      LEFT = 258,
      LEFTLINE = 259,
      LENGTH = 260,
      LESS = 261,
      LIB = 262,
      LIBACCESS = 263,
      LIBPARAMETER = 264,
      LIBRARY = 265,
      LILIAN = 266,
      LIMIT = 267,
      LIMITS = 268,
      LIN = 269,
      LINAGE = 270,
      LINE = 271,
      LINECOUNT = 272,
      LINES = 273,
      LINKAGE = 274,
      LIST = 275,
      LM = 276,
      LOCAL = 277,
      LOCK = 278,
      LONGMIXED = 279,
      LONGUPPER = 280,
      LOWER = 281,
      LOWLIGHT = 282,
      LU = 283,
      MAP = 284,
      MARGINS = 285,
      MAX = 286,
      MD = 287,
      MDECK = 288,
      MEMORY = 289,
      MERGE = 290,
      MESSAGE = 291,
      MIG = 292,
      MIXED = 293,
      MMDDYYYY = 294,
      MODE = 295,
      MODULES = 296,
      MOVE = 297,
      MULTIPLE = 298,
      MULTIPLY = 299,
      NAME = 300,
      NAMED = 301,
      NAT = 302,
      NATIONAL = 303,
      NATIVE = 304,
      NATLANG = 305,
      NEGATIVE = 306,
      NETWORK = 307,
      NEXT = 308,
      NN = 309,
      NO = 310,
      NOADATA = 311,
      NOADV = 312,
      NOALIAS = 313,
      NOAWO = 314,
      NOC = 315,
      NOCBLCARD = 316,
      NOCICS = 317,
      NOCOMPILE = 318,
      NOCPSM = 319,
      NOCURR = 320,
      NOCURRENCY = 321,
      NOD = 322,
      NODATEPROC = 323,
      NODBCS = 324,
      NODE = 325,
      NODEBUG = 326,
      NODECK = 327,
      NODIAGTRUNC = 328,
      NODLL = 329,
      NODP = 330,
      NODTR = 331,
      NODU = 332,
      NODUMP = 333,
      NODYN = 334,
      NODYNAM = 335,
      NOEDF = 336,
      NOEJPD = 337,
      NOEPILOG = 338,
      NOEXIT = 339,
      NOEXP = 340,
      NOEXPORTALL = 341,
      NOF = 342,
      NOFASTSRT = 343,
      NOFEPI = 344,
      NOFLAG = 345,
      NOFLAGMIG = 346,
      NOFLAGSTD = 347,
      NOFSRT = 348,
      NOGRAPHIC = 349,
      NOHOOK = 350,
      NOLENGTH = 351,
      NOLIB = 352,
      NOLINKAGE = 353,
      NOLIST = 354,
      NOMAP = 355,
      NOMD = 356,
      NOMDECK = 357,
      NONAME = 358,
      NONUM = 359,
      NONUMBER = 360,
      NOOBJ = 361,
      NOOBJECT = 362,
      NOOFF = 363,
      NOOFFSET = 364,
      NOOPSEQUENCE = 365,
      NOOPT = 366,
      NOOPTIMIZE = 367,
      NOOPTIONS = 368,
      NOP = 369,
      NOPFD = 370,
      NOPROLOG = 371,
      NORENT = 372,
      NOS = 373,
      NOSEP = 374,
      NOSEPARATE = 375,
      NOSEQ = 376,
      NOSEQUENCE = 377,
      NOSOURCE = 378,
      NOSPIE = 379,
      NOSQL = 380,
      NOSQLC = 381,
      NOSQLCCSID = 382,
      NOSSR = 383,
      NOSSRANGE = 384,
      NOSTDTRUNC = 385,
      NOT = 386,
      NOTERM = 387,
      NOTERMINAL = 388,
      NOTEST = 389,
      NOTHREAD = 390,
      NOTRIG = 391,
      NOVBREF = 392,
      NOWD = 393,
      NOWORD = 394,
      NOX = 395,
      NOXREF = 396,
      NOZWB = 397,
      NS = 398,
      NSEQ = 399,
      NSYMBOL = 400,
      NULLS = 401,
      NULL_ = 402,
      NUM = 403,
      NUMBER = 404,
      NUMERIC = 405,
      NUMPROC = 406,
      OBJ = 407,
      OBJECT = 408,
      OCCURS = 409,
      ODT = 410,
      OF = 411,
      OFF = 412,
      OFFSET = 413,
      OMITTED = 414,
      ON = 415,
      OP = 416,
      OPEN = 417,
      OPMARGINS = 418,
      OPSEQUENCE = 419,
      OPT = 420,
      OPTFILE = 421,
      OPTIMIZE = 422,
      OPTIONAL = 423,
      OPTIONS = 424,
      OR = 425,
      ORDER = 426,
      ORDERLY = 427,
      ORGANIZATION = 428,
      OTHER = 429,
      OUT = 430,
      OUTDD = 431,
      OUTPUT = 432,
      OVERFLOW = 433,
      OVERLINE = 434,
      OWN = 435,
      PADDING = 436,
      PAGE = 437,
      PASSWORD = 438,
      PERFORM = 439,
      PF = 440,
      PFD = 441,
      PGMN = 442,
      PGMNAME = 443,
      PH = 444,
      PIC = 445,
      PICTURE = 446,
      PLUS = 447,
      POINTER = 448,
      PORT = 449,
      POSITION = 450,
      POSITIVE = 451,
      PPTDBG = 452,
      PRINTER = 453,
      PRINTING = 454,
      PRIVATE = 455,
      PROCEDURE = 456,
      PROCEDURES = 457,
      PROCEED = 458,
      PROCESS = 459,
      PROGRAM = 460,
      PROGRAM_ID = 461,
      PROLOG = 462,
      PROMPT = 463,
      PURGE = 464,
      QUEUE = 465,
      QUOTE = 466,
      QUOTES = 467,
      RANDOM = 468,
      RD = 469,
      READ = 470,
      READER = 471,
      REAL = 472,
      RECEIVE = 473,
      RECEIVED = 474,
      RECORD = 475,
      RECORDING = 476,
      RECORDS = 477,
      RECURSIVE = 478,
      REDEFINES = 479,
      REEL = 480,
      REF = 481,
      REFERENCE = 482,
      REFERENCES = 483,
      RELATIVE = 484,
      RELEASE = 485,
      REMAINDER = 486,
      REMARKS = 487,
      REMOTE = 488,
      REMOVAL = 489,
      REMOVE = 490,
      RENAMES = 491,
      RENT = 492,
      REPLACE = 493,
      REPLACING = 494,
      REPORT = 495,
      REPORTING = 496,
      REPORTS = 497,
      REQUIRED = 498,
      RERUN = 499,
      RESERVE = 500,
      RESET = 501,
      RETURN = 502,
      RETURNING = 503,
      REVERSED = 504,
      REWIND = 505,
      REWRITE = 506,
      RF = 507,
      RH = 508,
      RIGHT = 509,
      RMODE = 510,
      ROUNDED = 511,
      RUN = 512,
      SAME = 513,
      SAVE = 514,
      SCREEN = 515,
      SD = 516,
      SEARCH = 517,
      SECTION = 518,
      SECURE = 519,
      SECURITY = 520,
      SEGMENT = 521,
      SELECT = 522,
      SEND = 523,
      SENTENCE = 524,
      SEP = 525,
      SEPARATE = 526,
      SEQ = 527,
      SEQUENCE = 528,
      SEQUENTIAL = 529,
      SET = 530,
      SHARED = 531,
      SHAREDBYALL = 532,
      SHAREDBYRUNUNIT = 533,
      SHARING = 534,
      SHORT = 535,
      SIGN = 536,
      SIZE = 537,
      SORT = 538,
      SOURCE = 539,
      SP = 540,
      SPACE = 541,
      SPACES = 542,
      SPIE = 543,
      SQL = 544,
      SQLC = 545,
      SQLCCSID = 546,
      SQLIMS = 547,
      SS = 548,
      SSR = 549,
      SSRANGE = 550,
      STANDARD = 551,
      START = 552,
      STATUS = 553,
      STD = 554,
      STOP = 555,
      STRING = 556,
      SUBTRACT = 557,
      SUM = 558,
      SUPPRESS = 559,
      SYMBOL = 560,
      SYMBOLIC = 561,
      SYNC = 562,
      SYNCHRONIZED = 563,
      SYSEIB = 564,
      SZ = 565,
      TABLE = 566,
      TALLY = 567,
      TALLYING = 568,
      TAPE = 569,
      TASK = 570,
      TERM = 571,
      TERMINAL = 572,
      TERMINATE = 573,
      TEST = 574,
      TEXT = 575,
      THAN = 576,
      THEN = 577,
      THREAD = 578,
      THROUGH = 579,
      THRU = 580,
      TIME = 581,
      TIMER = 582,
      TIMES = 583,
      TITLE = 584,
      TO = 585,
      TOP = 586,
      TRAILING = 587,
      TRIG = 588,
      TRUE = 589,
      TRUNC = 590,
      TRUNCATED = 591,
      TYPE = 592,
      TYPEDEF = 593,
      UE = 594,
      UNDERLINE = 595,
      UNIT = 596,
      UNSTRING = 597,
      UNTIL = 598,
      UP = 599,
      UPON = 600,
      UPPER = 601,
      USAGE = 602,
      USE = 603,
      USING = 604,
      VALUE = 605,
      VALUES = 606,
      VARYING = 607,
      VBREF = 608,
      VIRTUAL = 609,
      WAIT = 610,
      WD = 611,
      WHEN = 612,
      WITH = 613,
      WORD = 614,
      WORDS = 615,
      WORKING_STORAGE = 616,
      WRITE = 617,
      XMLPARSE = 618,
      XMLSS = 619,
      XOPTS = 620,
      XP = 621,
      XREF = 622,
      YEAR = 623,
      YEARWINDOW = 624,
      YW = 625,
      YYYYDDD = 626,
      YYYYMMDD = 627,
      ZERO = 628,
      ZEROES = 629,
      ZEROS = 630,
      ZWB = 631;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "ABORT",
                 "ACCEPT",
                 "ACCESS",
                 "ADATA",
                 "ADD",
                 "ADDRESS",
                 "ADV",
                 "ADVANCING",
                 "AFTER",
                 "ALIAS",
                 "ALIGNED",
                 "ALL",
                 "ALPHABET",
                 "ALPHABETIC",
                 "ALPHANUMERIC",
                 "ALSO",
                 "ALTER",
                 "ALTERNATE",
                 "AND",
                 "ANSI",
                 "ANY",
                 "APOST",
                 "AR",
                 "ARE",
                 "AREA",
                 "AREAS",
                 "ARITH",
                 "AS",
                 "ASCENDING",
                 "ASCII",
                 "ASSIGN",
                 "AT",
                 "ATTRIBUTE",
                 "AUTHOR",
                 "AUTO",
                 "AWO",
                 "BASIS",
                 "BEEP",
                 "BEFORE",
                 "BEGINNING",
                 "BELL",
                 "BIN",
                 "BINARY",
                 "BIT",
                 "BLANK",
                 "BLINK",
                 "BLOCK",
                 "BOTTOM",
                 "BOUNDS",
                 "BUF",
                 "BUFSIZE",
                 "BY",
                 "BYFUNCTION",
                 "BYTITLE",
                 "CALL",
                 "CANCEL",
                 "CAPABLE",
                 "CBL",
                 "CBLCARD",
                 "CCSVERSION",
                 "CD",
                 "CF",
                 "CH",
                 "CHAINING",
                 "CHANGED",
                 "CHANNEL",
                 "CHARACTER",
                 "CHARACTERS",
                 "CICS",
                 "CLASS",
                 "CLOSE",
                 "CO",
                 "COBOL",
                 "CODE",
                 "CODEPAGE",
                 "COL",
                 "COLLATING",
                 "COLUMN",
                 "COMMA",
                 "COMMITMENT",
                 "COMMON",
                 "COMMUNICATION",
                 "COMP",
                 "COMPAT",
                 "COMPILE",
                 "COMPUTATIONAL",
                 "COMPUTE",
                 "CONFIGURATION",
                 "CONTAINS",
                 "CONTENT",
                 "CONTINUE",
                 "CONTROL",
                 "CONTROLS",
                 "CONVENTION",
                 "CONVERTING",
                 "COPY",
                 "CORR",
                 "CORRESPONDING",
                 "COUNT",
                 "CP",
                 "CPP",
                 "CPSM",
                 "CRUNCH",
                 "CS",
                 "CURR",
                 "CURRENCY",
                 "CURSOR",
                 "DATA",
                 "DATE",
                 "DATEPROC",
                 "DAY",
                 "DBCS",
                 "DD",
                 "DE",
                 "DEBUG",
                 "DEBUGGING",
                 "DECK",
                 "DECLARATIVES",
                 "DEFAULT",
                 "DEFINITION",
                 "DELETE",
                 "DELIMITED",
                 "DELIMITER",
                 "DEPENDING",
                 "DESCENDING",
                 "DESTINATION",
                 "DETAIL",
                 "DFHRESP",
                 "DFHVALUE",
                 "DIAGTRUNC",
                 "DISABLE",
                 "DISK",
                 "DISPLAY",
                 "DIVIDE",
                 "DIVISION",
                 "DLI",
                 "DLL",
                 "DONTCARE",
                 "DOUBLE",
                 "DOWN",
                 "DP",
                 "DTR",
                 "DU",
                 "DUMP",
                 "DUPLICATES",
                 "DYN",
                 "DYNAM",
                 "DYNAMIC",
                 "EBCDIC",
                 "EDF",
                 "EGCS",
                 "EGI",
                 "EJECT",
                 "EJPD",
                 "ELSE",
                 "EMI",
                 "EN",
                 "ENABLE",
                 "END",
                 "ENDING",
                 "ENGLISH",
                 "ENTER",
                 "ENTRY",
                 "ENVIRONMENT",
                 "EOL",
                 "EOP",
                 "EOS",
                 "EPILOG",
                 "EQUAL",
                 "ERASE",
                 "ERROR",
                 "ESCAPE",
                 "ESI",
                 "EVALUATE",
                 "EVENT",
                 "EVERY",
                 "EXCEPTION",
                 "EXCI",
                 "EXCLUSIVE",
                 "EXEC",
                 "EXHIBIT",
                 "EXIT",
                 "EXP",
                 "EXPORT",
                 "EXPORTALL",
                 "EXTEND",
                 "EXTENDED",
                 "EXTERNAL",
                 "FALSE",
                 "FASTSRT",
                 "FD",
                 "FEPI",
                 "FILE",
                 "FILLER",
                 "FINAL",
                 "FIRST",
                 "FLAG",
                 "FLAGSTD",
                 "FOOTING",
                 "FOR",
                 "FROM",
                 "FSRT",
                 "FULL",
                 "FUNCTION",
                 "FUNCTIONNAME",
                 "GDS",
                 "GENERATE",
                 "GIVING",
                 "GLOBAL",
                 "GO",
                 "GOBACK",
                 "GRAPHIC",
                 "GREATER",
                 "GRID",
                 "GROUP",
                 "HEADING",
                 "HIGHLIGHT",
                 "HOOK",
                 "ID",
                 "IDENTIFICATION",
                 "IF",
                 "IMPLICIT",
                 "IMPORT",
                 "IN",
                 "INDEX",
                 "INDEXED",
                 "INDICATE",
                 "INITIAL",
                 "INITIALIZE",
                 "INITIATE",
                 "INPUT",
                 "INSPECT",
                 "INSTALLATION",
                 "INTDATE",
                 "INTEGER",
                 "INTO",
                 "INVALID",
                 "INVOKE",
                 "IS",
                 "JA",
                 "JP",
                 "JUST",
                 "JUSTIFIED",
                 "KA",
                 "KANJI",
                 "KEPT",
                 "KEY",
                 "KEYBOARD",
                 "LABEL",
                 "LANG",
                 "LANGUAGE",
                 "LAST",
                 "LB",
                 "LC",
                 "LD",
                 "LEADING",
                 "LEASM",
                 "LEFT",
                 "LEFTLINE",
                 "LENGTH",
                 "LESS",
                 "LIB",
                 "LIBACCESS",
                 "LIBPARAMETER",
                 "LIBRARY",
                 "LILIAN",
                 "LIMIT",
                 "LIMITS",
                 "LIN",
                 "LINAGE",
                 "LINE",
                 "LINECOUNT",
                 "LINES",
                 "LINKAGE",
                 "LIST",
                 "LM",
                 "LOCAL",
                 "LOCK",
                 "LONGMIXED",
                 "LONGUPPER",
                 "LOWER",
                 "LOWLIGHT",
                 "LU",
                 "MAP",
                 "MARGINS",
                 "MAX",
                 "MD",
                 "MDECK",
                 "MEMORY",
                 "MERGE",
                 "MESSAGE",
                 "MIG",
                 "MIXED",
                 "MMDDYYYY",
                 "MODE",
                 "MODULES",
                 "MOVE",
                 "MULTIPLE",
                 "MULTIPLY",
                 "NAME",
                 "NAMED",
                 "NAT",
                 "NATIONAL",
                 "NATIVE",
                 "NATLANG",
                 "NEGATIVE",
                 "NETWORK",
                 "NEXT",
                 "NN",
                 "NO",
                 "NOADATA",
                 "NOADV",
                 "NOALIAS",
                 "NOAWO",
                 "NOC",
                 "NOCBLCARD",
                 "NOCICS",
                 "NOCOMPILE",
                 "NOCPSM",
                 "NOCURR",
                 "NOCURRENCY",
                 "NOD",
                 "NODATEPROC",
                 "NODBCS",
                 "NODE",
                 "NODEBUG",
                 "NODECK",
                 "NODIAGTRUNC",
                 "NODLL",
                 "NODP",
                 "NODTR",
                 "NODU",
                 "NODUMP",
                 "NODYN",
                 "NODYNAM",
                 "NOEDF",
                 "NOEJPD",
                 "NOEPILOG",
                 "NOEXIT",
                 "NOEXP",
                 "NOEXPORTALL",
                 "NOF",
                 "NOFASTSRT",
                 "NOFEPI",
                 "NOFLAG",
                 "NOFLAGMIG",
                 "NOFLAGSTD",
                 "NOFSRT",
                 "NOGRAPHIC",
                 "NOHOOK",
                 "NOLENGTH",
                 "NOLIB",
                 "NOLINKAGE",
                 "NOLIST",
                 "NOMAP",
                 "NOMD",
                 "NOMDECK",
                 "NONAME",
                 "NONUM",
                 "NONUMBER",
                 "NOOBJ",
                 "NOOBJECT",
                 "NOOFF",
                 "NOOFFSET",
                 "NOOPSEQUENCE",
                 "NOOPT",
                 "NOOPTIMIZE",
                 "NOOPTIONS",
                 "NOP",
                 "NOPFD",
                 "NOPROLOG",
                 "NORENT",
                 "NOS",
                 "NOSEP",
                 "NOSEPARATE",
                 "NOSEQ",
                 "NOSEQUENCE",
                 "NOSOURCE",
                 "NOSPIE",
                 "NOSQL",
                 "NOSQLC",
                 "NOSQLCCSID",
                 "NOSSR",
                 "NOSSRANGE",
                 "NOSTDTRUNC",
                 "NOT",
                 "NOTERM",
                 "NOTERMINAL",
                 "NOTEST",
                 "NOTHREAD",
                 "NOTRIG",
                 "NOVBREF",
                 "NOWD",
                 "NOWORD",
                 "NOX",
                 "NOXREF",
                 "NOZWB",
                 "NS",
                 "NSEQ",
                 "NSYMBOL",
                 "NULLS",
                 "NULL_",
                 "NUM",
                 "NUMBER",
                 "NUMERIC",
                 "NUMPROC",
                 "OBJ",
                 "OBJECT",
                 "OCCURS",
                 "ODT",
                 "OF",
                 "OFF",
                 "OFFSET",
                 "OMITTED",
                 "ON",
                 "OP",
                 "OPEN",
                 "OPMARGINS",
                 "OPSEQUENCE",
                 "OPT",
                 "OPTFILE",
                 "OPTIMIZE",
                 "OPTIONAL",
                 "OPTIONS",
                 "OR",
                 "ORDER",
                 "ORDERLY",
                 "ORGANIZATION",
                 "OTHER",
                 "OUT",
                 "OUTDD",
                 "OUTPUT",
                 "OVERFLOW",
                 "OVERLINE",
                 "OWN",
                 "PADDING",
                 "PAGE",
                 "PASSWORD",
                 "PERFORM",
                 "PF",
                 "PFD",
                 "PGMN",
                 "PGMNAME",
                 "PH",
                 "PIC",
                 "PICTURE",
                 "PLUS",
                 "POINTER",
                 "PORT",
                 "POSITION",
                 "POSITIVE",
                 "PPTDBG",
                 "PRINTER",
                 "PRINTING",
                 "PRIVATE",
                 "PROCEDURE",
                 "PROCEDURES",
                 "PROCEED",
                 "PROCESS",
                 "PROGRAM",
                 "PROGRAM_ID",
                 "PROLOG",
                 "PROMPT",
                 "PURGE",
                 "QUEUE",
                 "QUOTE",
                 "QUOTES",
                 "RANDOM",
                 "RD",
                 "READ",
                 "READER",
                 "REAL",
                 "RECEIVE",
                 "RECEIVED",
                 "RECORD",
                 "RECORDING",
                 "RECORDS",
                 "RECURSIVE",
                 "REDEFINES",
                 "REEL",
                 "REF",
                 "REFERENCE",
                 "REFERENCES",
                 "RELATIVE",
                 "RELEASE",
                 "REMAINDER",
                 "REMARKS",
                 "REMOTE",
                 "REMOVAL",
                 "REMOVE",
                 "RENAMES",
                 "RENT",
                 "REPLACE",
                 "REPLACING",
                 "REPORT",
                 "REPORTING",
                 "REPORTS",
                 "REQUIRED",
                 "RERUN",
                 "RESERVE",
                 "RESET",
                 "RETURN",
                 "RETURNING",
                 "REVERSED",
                 "REWIND",
                 "REWRITE",
                 "RF",
                 "RH",
                 "RIGHT",
                 "RMODE",
                 "ROUNDED",
                 "RUN",
                 "SAME",
                 "SAVE",
                 "SCREEN",
                 "SD",
                 "SEARCH",
                 "SECTION",
                 "SECURE",
                 "SECURITY",
                 "SEGMENT",
                 "SELECT",
                 "SEND",
                 "SENTENCE",
                 "SEP",
                 "SEPARATE",
                 "SEQ",
                 "SEQUENCE",
                 "SEQUENTIAL",
                 "SET",
                 "SHARED",
                 "SHAREDBYALL",
                 "SHAREDBYRUNUNIT",
                 "SHARING",
                 "SHORT",
                 "SIGN",
                 "SIZE",
                 "SORT",
                 "SOURCE",
                 "SP",
                 "SPACE",
                 "SPACES",
                 "SPIE",
                 "SQL",
                 "SQLC",
                 "SQLCCSID",
                 "SQLIMS",
                 "SS",
                 "SSR",
                 "SSRANGE",
                 "STANDARD",
                 "START",
                 "STATUS",
                 "STD",
                 "STOP",
                 "STRING",
                 "SUBTRACT",
                 "SUM",
                 "SUPPRESS",
                 "SYMBOL",
                 "SYMBOLIC",
                 "SYNC",
                 "SYNCHRONIZED",
                 "SYSEIB",
                 "SZ",
                 "TABLE",
                 "TALLY",
                 "TALLYING",
                 "TAPE",
                 "TASK",
                 "TERM",
                 "TERMINAL",
                 "TERMINATE",
                 "TEST",
                 "TEXT",
                 "THAN",
                 "THEN",
                 "THREAD",
                 "THROUGH",
                 "THRU",
                 "TIME",
                 "TIMER",
                 "TIMES",
                 "TITLE",
                 "TO",
                 "TOP",
                 "TRAILING",
                 "TRIG",
                 "TRUE",
                 "TRUNC",
                 "TRUNCATED",
                 "TYPE",
                 "TYPEDEF",
                 "UE",
                 "UNDERLINE",
                 "UNIT",
                 "UNSTRING",
                 "UNTIL",
                 "UP",
                 "UPON",
                 "UPPER",
                 "USAGE",
                 "USE",
                 "USING",
                 "VALUE",
                 "VALUES",
                 "VARYING",
                 "VBREF",
                 "VIRTUAL",
                 "WAIT",
                 "WD",
                 "WHEN",
                 "WITH",
                 "WORD",
                 "WORDS",
                 "WORKING_STORAGE",
                 "WRITE",
                 "XMLPARSE",
                 "XMLSS",
                 "XOPTS",
                 "XP",
                 "XREF",
                 "YEAR",
                 "YEARWINDOW",
                 "YW",
                 "YYYYDDD",
                 "YYYYMMDD",
                 "ZERO",
                 "ZEROES",
                 "ZEROS",
                 "ZWB"
             };


    public final static int numTokenKinds = 631;
    public final static boolean isValidForParser = false;
}
